services:
  dev:
    image: ghcr.io/getzola/zola:v0.19.2
    ports:
      - ${ZOLA_RELOAD_PORT:-8086}:${ZOLA_RELOAD_PORT:-8086}
      - ${ZOLA_SERVE_PORT:-8085}:${ZOLA_SERVE_PORT:-8085}
    volumes:
      - ./:/app/
    working_dir: /app
    command: serve --drafts --interface ${ZOLA_SERVE_IFACE:-0.0.0.0} --port ${ZOLA_SERVE_PORT:-8085} --base-url ${ZOLA_SERVE_URL:-localhost}
  builder:
    image: ghcr.io/getzola/zola:v0.18.0
    volumes:
      - ./:/app/
    working_dir: /app
    command: build
